# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  unittest-27:
    working_directory: ~/scalyr-agent-2
    docker:
      - image: circleci/python:2.7-jessie-browsers
        environment:
          PYTHONPATH=./scalyr_agent/third_party
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "dev-requirements.txt" }}
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r dev-requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            source venv/bin/activate
            python run_tests.py

      - store_artifacts:
          path: xunit.xml

      - store_artifacts:
          path: cover/

  unittest-26:
    docker:
      - image: circleci/python:2.7-jessie-browsers
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: docker run -it -e TEST_BRANCH=${CIRCLE_BRANCH} edwardchee/scalyr-agent-ci:python26 /tmp/run_unittests.sh

  smoke-standalone-27:
    docker:
      - image: circleci/python:2.7-jessie-browsers
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: docker run -it -e TEST_BRANCH=${CIRCLE_BRANCH} -e MAX_WAIT=300 -e PYTHON_VERSION=2.7 -e SCALYR_API_KEY=${SCALYR_API_KEY} -e READ_API_KEY=${READ_API_KEY} -e SCALYR_SERVER=${SCALYR_SERVER} scalyr/scalyr-agent-ci-smoketest:v1.1 /tmp/smoketest_standalone.sh

  smoke-standalone-26:
    docker:
      - image: circleci/python:2.7-jessie-browsers
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: docker run -it -e TEST_BRANCH=${CIRCLE_BRANCH} -e MAX_WAIT=300 -e PYTHON_VERSION=2.6 -e SCALYR_API_KEY=${SCALYR_API_KEY} -e READ_API_KEY=${READ_API_KEY} -e SCALYR_SERVER=${SCALYR_SERVER} scalyr/scalyr-agent-ci-smoketest:v1.1 /tmp/smoketest_standalone.sh

  smoke-standalone-25:
    docker:
      - image: circleci/python:2.7-jessie-browsers
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: docker run -it -e TEST_BRANCH=${CIRCLE_BRANCH} -e MAX_WAIT=300 -e PYTHON_VERSION=2.5 -e SCALYR_API_KEY=${SCALYR_API_KEY} -e READ_API_KEY=${READ_API_KEY} -e SCALYR_SERVER=${SCALYR_SERVER} scalyr/scalyr-agent-ci-smoketest:v1.1 /tmp/smoketest_standalone.sh

  smoke-standalone-24:
    docker:
      - image: circleci/python:2.7-jessie-browsers
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: docker run -it -e TEST_BRANCH=${CIRCLE_BRANCH} -e MAX_WAIT=300 -e PYTHON_VERSION=2.4 -e SCALYR_API_KEY=${SCALYR_API_KEY} -e READ_API_KEY=${READ_API_KEY} -e SCALYR_SERVER=${SCALYR_SERVER} scalyr/scalyr-agent-ci-smoketest:v1.1 /tmp/smoketest_standalone.sh

  smoke-docker-json:
    docker:
      - image: circleci/python:2.7-jessie-browsers
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-docker-json-{{ checksum "dev-requirements.txt" }}
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r dev-requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-docker-json-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: source ./.circleci/smoketest_docker.sh scalyr/scalyr-agent-ci-smoketest:v1.1 json 300 /tmp/workdir_smoke_docker_json ${CIRCLE_BRANCH}

  smoke-docker-syslog:
    docker:
      - image: circleci/python:2.7-jessie-browsers
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-docker-json-{{ checksum "dev-requirements.txt" }}
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r dev-requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-docker-json-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: source ./.circleci/smoketest_docker.sh scalyr/scalyr-agent-ci-smoketest:v1.1 syslog 300 /tmp/workdir_smoke_docker_syslog ${CIRCLE_BRANCH}

workflows:
  version: 2
  unittest:
    jobs:
      - unittest-27
      - unittest-26
      - smoke-standalone-27
      - smoke-standalone-26
      - smoke-standalone-25
      - smoke-standalone-24
      - smoke-docker-json
      - smoke-docker-syslog
